[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.2.10"
version_files = [
    "version.php:VERSION",
    "resources/js/package.json:version"
]
update_changelog_on_bump = true
major_version_zero = true
