version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mobmash:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DBNAME: mydatabase
      UPDATER_CONTACT_EMAIL: dev@localhost
      GENERAL_CONTACT_EMAIL: dev@localhost
      PRIVACY_CONTACT: John Doe
      PRIVACY_CONTACT_EMAIL: dev@localhost
    depends_on:
      - postgres
    volumes:
      - ../:/var/www/mobmash:Z
    ports:
      - "8080:8080"

volumes:
  postgres_data: